### ISSUE TITLE
how to increase stream request timeout more than default command timeout of cypress 

### ISSUE THREAD

**Issue by nehalbadelhafez** [lensesio/cypress-websocket-testing#12]
I need to increase stream request timeout without changing default command timeout, in repo it is written to use wrap but I really don't know how to use a wrap with this option if there an example to help.

**Comment by nehalbadelhafez** [comment]
I found the solution by adding stream timeout within options.

**Comment by nehalbadelhafez** [comment]
actually, after a while, it is not working again, so If there is an example to demonstrate how to increase stream timeout with cypress without changing the default command timeout.

**Comment by dsebastian** [comment]
Hi @nehalbadelhafez , have you tried the example found here? 
https://github.com/lensesio/cypress-websocket-testing/blob/master/examples/cypress/integration/examples/streamRequest.spec.ts#L73
It shows how to wrap the streamRequest to bypass the timeout.

**Comment by nehalbadelhafez** [comment]
Hi, sorry I didn't see this example. I will check it, Thank you so much.
