### ISSUE TITLE
the cy.stream just runs and immediately ends.

### ISSUE THREAD

**Issue by vince-lynch** [lensesio/cypress-websocket-testing#14]
Hey, 
for me the cy.stream just runs and immediately ends.
It doesn't hold the connection open.

I will continue to look into, but if you have any advice?

Many thanks

**Comment by dsebastian** [comment]
Hi Vince,
It shouldn't close unless your BE is closing the stream. If you add a few more details about your case it would help out:

Is the BE sending a heartbeat? How soon does it close the connection? Can you post a snipet to reproduce the issue?

Also have you tried with the example from the repo? Does it have the same problem?

**Comment by dsebastian** [comment]
Closing for the moment. Feel free to reopen and ideally provide with an example to reproduce. Thanks.

**Comment by pascalporedda** [comment]
If anyone ever comes across this:

I fiddled with it for 3 hours and all I had to do was to add a simple `return false;` at the end of my message handler.
