### ISSUE TITLE
In javascript example where i should put channel name at ? cy.stream! command

### ISSUE THREAD

**Issue by nehalbadelhafez** [lensesio/cypress-websocket-testing#7]
what I need to do is to subscribe on the channel and wait until special message come, I have tried cy.stream with subscribe but I can't find where I should but channel name to get a confirmation message on subscription

**Comment by dsebastian** [comment]
Hi @nehalbadelhafez , what do you mean by "channel name"?

**Comment by nehalbadelhafez** [comment]
var payload = {
  command: "subscribe",
  identifier: '{"channel":"LogsChannel"}'
};
like this, as I have number of channel and I need to subscribe to specific one

**Comment by dsebastian** [comment]
You can use the startUpMessage property of the cy.streamRequest, as in the docs. That payload will be sent once the connection has been made, and you should set takeWhileFn to check for the confirmation message for your subscription.

**Comment by nehalbadelhafez** [comment]
could you please show me an example, also the docs where ? as the docs contains typescript I need javascript example

**Comment by dsebastian** [comment]
See this example: https://github.com/lensesio/cypress-websocket-testing/blob/master/examples/cypress/integration/examples/streamRequest.spec.ts#L60

It's the same in Javascript, just remove the types.

**Comment by nehalbadelhafez** [comment]
ok I will try it thank you so much

**Comment by dsebastian** [comment]
Closing issue then.
